trigger:
  branches:
    include:
      - main # Triggers the pipeline automatically on commits to main branch

pool:
  vmImage: 'ubuntu-latest' # Uses a Microsoft-managed Linux agent pool

variables:
 - name: tfvarsFile
   value: "terraform.tfvars"
 - name:  azureServiceConnection
   value: "tacowagon-dev"
 - name:  backendRG
   value: "cloud-shell-storage-centralindia"
 - name: backendStorage
   value: "csg1003200057bb97a0"
 - name: backendContainer
   value: "tfstate"
 - name: backendKey
   value: "terraform.tfstate"
 - name: terraformWorkingDirectory
   value: "$(System.DefaultWorkingDirectory)"

# Reference your Azure DevOps Service Connection name here
   #azureServiceConnection: 'tacowagon-dev'

   # Remote backend configuration details
   # backendRG: 'cloud-shell-storage-centralindia'
   # backendStorage: 'csg1003200057bb97a0'
   # backendContainer: 'storage-account-container-blob'
   # backendKey: 'gajBD14R4xodhCkPzlEiueTw3nvHK8eQbmQ6r97j6ZdCbfvne2lCdRB7XY9vkjDlHlVSfri1BPDS+ASthgtluQ=='
  
  # Specify the path where your Terraform files (.tf) live
  #terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)'

stages:
  # ----------------------------------------
  # Stage 1: Run Terraform Plan
  # ----------------------------------------
  - stage: TerraformPlan
    displayName: 'Terraform Plan'
    jobs:
      - job: Plan
        displayName: 'Validate and Plan Changes'
        steps:
          # Step 1: Install Terraform dynamically on the agent
          - task: TerraformInstaller@1
            displayName: 'Install Terraform (Latest)'
            inputs:
              terraformVersion: '1.15.6'

          # Step 2: Proceed with your regular Terraform tasks.
          # Initialize working directory and Azure backend remote state
          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(terraformWorkingDirectory)'
              backendServiceArm: '$(azureServiceConnection)'
              backendAzureRmResourceGroupName: '$(backendRG)'
              backendAzureRmStorageAccountName: '$(backendStorage)'
              backendAzureRmContainerName: '$(backendContainer)'
              backendAzureRmKey: '$(backendKey)'

        # Step 3: Run Validation check to catch syntax errors
          - task: TerraformTaskV4@4
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(terraformWorkingDirectory)'

        # Step 4: Generate the plan file and save it as an artifact output
          - task: TerraformTaskV4@4
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(terraformWorkingDirectory)'
              environmentServiceNameAzureRM: '$(azureServiceConnection)'
              #commandOptions: '-out=$(Pipeline.Workspace)/tfplan'
              commandOptions: '-out=tfplan'

        # Step 5: Publish the generated plan file to the pipeline run
          #- publish: $(Pipeline.Workspace)/tfplan

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Plan'
            inputs:
              targetPath: '$(terraformWorkingDirectory)'
              artifact: 'tfplan'

  # ----------------------------------------
  # Stage 2: Run Terraform Apply
  # ----------------------------------------
  - stage: TerraformApply
    displayName: 'Terraform Apply'
    dependsOn: TerraformPlan
    condition: succeeded('TerraformPlan') # Only run if the Plan stage completes successfully
    jobs:
      # Deployment jobs natively support manual environment checks and approvals
      - deployment: Apply
        displayName: 'Deploy Infrastructure'
        environment: 'Production' # Link to ADO Environment to enforce manual approvals
        strategy:
          runOnce:
            deploy:
              steps:
                # Step 1: Re-install Terraform on the deployment agent
                - task: TerraformInstaller@1
                  displayName: 'Install Terraform (Latest)'
                  inputs:
                    terraformVersion: '1.15.6'

                # Step 2:  Download the generated blueprint file from stage 1
                - task: DownloadPipelineArtifact@2
                  displayName: 'Download Plan'
                  inputs:
                    artifact: 'tfplan'
                    path: '$(terraformWorkingDirectory)'

                # Step 3: Re-initialize backend for the deployment stage context
                - task: TerraformTaskV4@4
                  displayName: 'Terraform Init'
                  inputs:
                    provider: 'azurerm'
                    command: 'init' 
          
                    workingDirectory: '$(terraformWorkingDirectory)'
                    backendServiceArm: '$(azureServiceConnection)'
                    backendAzureRmResourceGroupName: '$(backendRG)'
                    backendAzureRmStorageAccountName: '$(backendStorage)'
                    backendAzureRmContainerName: '$(backendContainer)'
                    backendAzureRmKey: '$(backendKey)'

                # Step 4: Execute infrastructure changes using the downloaded plan
                - task: TerraformTaskV4@4
                  displayName: 'Terraform Apply'
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    workingDirectory: '$(terraformWorkingDirectory)'
                    environmentServiceNameAzureRM: '$(azureServiceConnection)'
                    commandOptions: '$(Pipeline.Workspace)/tfplan/tfplan'

                
